import 'dart:io';
import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'package:sqlite3_flutter_libs/sqlite3_flutter_libs.dart';

part 'database.g.dart'; // generated by build_runner - do not edit by hand

/// Unit of sale for a product. Hardware/quincaillerie-specific:
/// most competitor apps (built for grocery) only support `piece`.
enum ProductUnit { piece, meter, kg, liter }

enum MovementType { stockIn, stockOut, adjustment }

enum PaymentMethod { cash, check, credit } // "credit" = client account/ardoise

/// -----------------------------------------------------------------------
/// TABLES
/// Every table has a `synced` column. This is the entire offline-first
/// strategy in one field: write locally first, flip `synced` to true only
/// after the row is confirmed pushed to Supabase.
/// -----------------------------------------------------------------------

class Products extends Table {
  TextColumn get id => text()(); // uuid, generated client-side
  TextColumn get storeId => text()();
  TextColumn get name => text()();
  TextColumn get barcode => text().unique()(); // our own generated code
  TextColumn get category => text().withDefault(const Constant(''))();
  IntColumn get unit => intEnum<ProductUnit>()();
  RealColumn get buyPrice => real().withDefault(const Constant(0))();
  RealColumn get sellPrice => real().withDefault(const Constant(0))();
  RealColumn get quantity => real().withDefault(const Constant(0))();
  RealColumn get lowStockThreshold => real().withDefault(const Constant(5))();
  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();
  DateTimeColumn get updatedAt => dateTime().withDefault(currentDateAndTime)();
  BoolColumn get synced => boolean().withDefault(const Constant(false))();

  @override
  Set<Column> get primaryKey => {id};
}

class StockMovements extends Table {
  TextColumn get id => text()();
  TextColumn get productId => text().references(Products, #id)();
  TextColumn get storeId => text()();
  TextColumn get userId => text()();
  IntColumn get type => intEnum<MovementType>()();
  RealColumn get quantity => real()();
  TextColumn get note => text().withDefault(const Constant(''))();
  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();
  BoolColumn get synced => boolean().withDefault(const Constant(false))();

  @override
  Set<Column> get primaryKey => {id};
}

class Sales extends Table {
  TextColumn get id => text()();
  TextColumn get storeId => text()();
  TextColumn get userId => text()();
  RealColumn get total => real()();
  IntColumn get paymentMethod => intEnum<PaymentMethod>()();
  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();
  BoolColumn get synced => boolean().withDefault(const Constant(false))();

  @override
  Set<Column> get primaryKey => {id};
}

class SaleItems extends Table {
  TextColumn get id => text()();
  TextColumn get saleId => text().references(Sales, #id)();
  TextColumn get productId => text().references(Products, #id)();
  RealColumn get quantity => real()();
  RealColumn get unitPrice => real()();
  RealColumn get subtotal => real()();

  @override
  Set<Column> get primaryKey => {id};
}

@DriftDatabase(tables: [Products, StockMovements, Sales, SaleItems])
class AppDatabase extends _$AppDatabase {
  AppDatabase() : super(_openConnection());

  @override
  int get schemaVersion => 1;

  // ---- Convenience queries used throughout the app ----

  Future<List<Product>> allProducts(String storeId) =>
      (select(products)..where((p) => p.storeId.equals(storeId))).get();

  Stream<List<Product>> watchProducts(String storeId) =>
      (select(products)..where((p) => p.storeId.equals(storeId))).watch();

  Future<List<Product>> lowStockProducts(String storeId) => (select(products)
        ..where((p) =>
            (p.storeId.equals(storeId)) &
            (p.quantity.isSmallerOrEqual(p.lowStockThreshold))))
      .get();

  /// Everything not yet pushed to the server - used by SyncService.
  Future<List<Product>> unsyncedProducts() =>
      (select(products)..where((p) => p.synced.equals(false))).get();

  Future<List<StockMovement>> unsyncedMovements() =>
      (select(stockMovements)..where((m) => m.synced.equals(false))).get();

  Future<List<Sale>> unsyncedSales() =>
      (select(sales)..where((s) => s.synced.equals(false))).get();
}

LazyDatabase _openConnection() {
  return LazyDatabase(() async {
    final dbFolder = await getApplicationDocumentsDirectory();
    final file = File(p.join(dbFolder.path, 'quincaillerie.sqlite'));
    // Needed on Android to bundle the right sqlite3 native lib.
    await applyWorkaroundToOpenSqlite3OnOldAndroidVersions();
    return NativeDatabase.createInBackground(file);
  });
}
